### PR TITLE
Add user attributes to examples

### PR DESCRIPTION
**Pull request by stalbot**

### CODE REVIEW

**Comment by juan-restrepo** [comment]
@stalbot, @dthorpe: Should the order in which the parameters are added to the string to sign be important?

**Comment by npickens** [comment]
@juan-restrepo Yup, definitely. Looker verifies the signature passed to it by performing the same computation. So if any of the parameters are out of order, the signature won't validate.

**Comment by juan-restrepo** [comment]
Thanks! It took me hours of debugging -_-. My bad. I'll add a comment to the file so no one has to go through this again

**Comment by juan-restrepo** [comment]
@npickens #24 should help someone in the future.

**Pull request merged**
